#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Mon Oct 21 11:35:15 2013

import wx
import mp3datastorage #for deletion method

# begin wxGlade: extracode
# end wxGlade


class check_del(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: check_del.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_3 = wx.StaticText(self, -1, "Are you sure you\nwish to wipe database?", style=wx.ALIGN_CENTRE)
        self.button_1 = wx.Button(self, -1, "Yes")
        self.button_2 = wx.Button(self, -1, "No")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.yes_del, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.no_del, self.button_2)
        # end wxGlade

        self.name = open("config.cfg", "r").readline().rstrip()

    def __set_properties(self):
        # begin wxGlade: check_del.__set_properties
        self.SetTitle("delete confirm")
        self.label_3.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Droid Sans"))
        self.SetBackgroundColour(wx.Colour(127, 170, 191))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: check_del.__do_layout
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6.Add(self.label_3, 0, wx.EXPAND, 0)
        sizer_6.Add((20, 20), 0, 0, 0)
        sizer_7.Add((56, 20), 0, 0, 0)
        sizer_7.Add(self.button_1, 0, 0, 0)
        sizer_7.Add((20, 20), 0, 0, 0)
        sizer_7.Add(self.button_2, 0, 0, 0)
        sizer_6.Add(sizer_7, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_6)
        sizer_6.Fit(self)
        self.Layout()
        # end wxGlade

    def yes_del(self, event):  # wxGlade: check_del.<event_handler>
        mp3datastorage.SQLmgr(self.name).wipe_database(self.name)
        self.Close()

    def no_del(self, event):  # wxGlade: check_del.<event_handler>
        self.Close()

# end of class check_del
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_2 = check_del(None, -1, "")
    app.SetTopWindow(frame_2)
    frame_2.Show()
    app.MainLoop()
